### ISSUE TITLE
Some usage differences seem to be missing from the comparison

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/hl7-diff-tool-frontend#11]
Here are the files I use
[profiles.zip](https://github.com/usnistgov/hl7-diff-tool-frontend/files/8624786/profiles.zip)

And the configuration:
![image](https://user-images.githubusercontent.com/13591511/166746832-f4958930-291b-4e38-a6e1-c3b263440965.png)

Here's what I see (I changed to "all changes")
![image](https://user-images.githubusercontent.com/13591511/166746974-f05e8431-2ebc-423f-85c6-c287583c1883.png)

The problem is that there are usage changes in the second segment (SFT), and I can see them if in change the configuration to start with
![image](https://user-images.githubusercontent.com/13591511/166747465-fdaa4dd0-b1b5-42c5-a162-3aaa910b288c.png)

Then I can expand the SFT segment and see differences:
![image](https://user-images.githubusercontent.com/13591511/166747627-c6cedda1-9638-4748-a70b-4070c94132b3.png)

**Comment by mellouli-dev** [comment]
@carolinerosin Isn't this how it should be? Since the change in SFT segment is in the component, which is in the datatype used by the field. Since Datatype is not checked in the configuration, we don't compare that datatypes.

**Comment by carolinerosin** [comment]
I see what you mean. 
My original thought was that is I only check usage, I'll get all the usage differences (including in components and subcomponents).
What I understand is that unchecking datatype acts like a filter : we won't see the usage differences for components or subcomponents.
I think this could be confusing, but maybe that's exactly what the group wanted ? Let's check with them to be sure.
